=apiVersion: v1
kind: Service
metadata:
  name: deploycrm-service
  labels:
    app: deploycrm-app
spec:
  type: LoadBalancer  # Exposes the service outside the cluster
  ports:
    - port: 80  # Exposes port 80 to the outside world
      targetPort: 8080  # Forwards to port 8080 inside the container
  selector:
    app: deploycrm-app
